import '@xyflow/react/dist/style.css'
import { ReactFlowProvider } from '@xyflow/react'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactFlowProvider>{children}</ReactFlowProvider>
      </body>
    </html>
  )
}
